USE ENTERPRISE_11S20018
GO --1
CREATE TABLE MANAGER
(MANAGER_ID		INT				NOT NULL,
MANAGER_NAME	VARCHAR(10)		NOT NULL,
SALARY			DECIMAL(10,2)	NOT NULL,
PRIMARY KEY		(MANAGER_ID));
GO --2 
INSERT INTO MANAGER (MANAGER_ID, MANAGER_NAME, SALARY)
	VALUES	(66928, 'Thomas', 5000.00),
			(65646, 'Merry', 7000.00),
			(67832, 'Adeline', 5500.00);
SELECT * FROM MANAGER
GO --3
ALTER TABLE MANAGER
	ADD COMMISSION DECIMAL(7,2); 
SELECT * FROM MANAGER
GO --4
UPDATE MANAGER
SET SALARY = 7500.00
WHERE MANAGER_ID = 67832;
SELECT * FROM MANAGER
GO --5
SELECT MANAGER_NAME, SALARY
FROM MANAGER
WHERE SALARY > 6000.00
	AND MANAGER_NAME LIKE '%Y';
GO --6
--ALTER TABLE EMPLOYEES
--ADD CONSTRAINT fk_MANAGER_ID FOREIGN KEY (MANAGER_ID) REFERENCES MANAGER (MANAGER_ID);
SELECT EMP_ID,DEPT_ID,EMP_NAME,JOB_NAME,MANAGER_ID,HIRE_DATE,SALARY,COMMISSION
FROM EMPLOYEES
WHERE JOB_NAME 
	  NOT IN ('CLERK','ANALYST');
GO --7
SELECT JOB_NAME "NamaPekerjaan", COUNT(JOB_NAME)
FROM EMPLOYEES
GROUP BY JOB_NAME
GO --8
SELECT EMP_NAME, SALARY
FROM EMPLOYEES
GO --9
SELECT MIN_SAL, MAX_SAL
FROM SALARY_GRADE
WHERE MIN_SAL > 1500
	AND MAX_SAL < 2500;
GO --10
SELECT MIN_SAL, MAX_SAL
FROM SALARY_GRADE
WHERE MIN_SAL > 1500
	OR MAX_SAL < 2500;
GO --11
SELECT * FROM EMPLOYEES
WHERE EMP_ID LIKE '6___4'
GO --12
SELECT EMP_ID, EMP_NAME, SALARY, COMMISSION
FROM EMPLOYEES
GO --13
SELECT EMP_ID, EMP_NAME
FROM EMPLOYEES
WHERE COMMISSION IS NOT NULL
GO --14
SELECT EMP_NAME "NamaPegawai", JOB_NAME "NamaPekerjaan", DEPT_ID "IDDepartement"
FROM EMPLOYEES
WHERE SALARY > 1500
	AND DEPT_ID = 1001;
GO --15
SELECT * FROM EMPLOYEES
WHERE HIRE_DATE < '1992-01-01'
GO --16
SELECT EMP_ID "IDPegawai", EMP_NAME "NamaPegawai", SALARY "Gaji", SALARY+(SALARY*0.15) "KenaikanGaji"
FROM EMPLOYEES
WHERE SALARY+(SALARY*0.15) > 2500
GO --17
SELECT JOB_NAME "NamaPekerjaan", AVG(SALARY) "AVGGaji", AVG(COMMISSION+SALARY) "AVGGajiKomisi"
FROM EMPLOYEES
GROUP BY JOB_NAME
HAVING AVG(SALARY) > 1500
GO --18
SELECT EMP_ID, EMP_NAME, JOB_NAME
FROM EMPLOYEES
WHERE JOB_NAME = 'SALESMAN'
	AND DEPT_ID = 3001
	AND COMMISSION < SALARY
GROUP BY JOB_NAME, EMP_NAME, EMP_ID
HAVING SUM((SALARY+COMMISSION)*12) < 25000
ORDER BY SUM((SALARY+COMMISSION)*12)
