USE ENTERPRISE_11S20018
GO --1
SELECT * FROM EMPLOYEES
GO --2
SELECT EMP_NAME, JOB_NAME, MANAGER_ID
FROM EMPLOYEES
GO --3
SELECT EMP_NAME, JOB_NAME, MANAGER_ID
FROM EMPLOYEES
WHERE DEPT_ID = 1001
GO --4
SELECT DEPT_NAME "NAMADEPARTEMENT", DEPT_LOCATION "LOKASIDEPARTEMENT"
FROM DEPARTEMENT
GO --5
SELECT EMP_NAME, SALARY, SALARY+(SALARY*0.2) "SALARYINCREASE"
FROM EMPLOYEES
WHERE JOB_NAME = 'SALESMAN'
GO --6
SELECT EMP_ID "IDPEGAWAI", EMP_NAME "NAMAPEGAWAI", MANAGER_ID "IDMANAGER", SALARY
FROM EMPLOYEES
WHERE SALARY < 3000;
GO --7
SELECT EMP_ID, EMP_NAME
FROM EMPLOYEES
WHERE SALARY NOT BETWEEN 1500 AND 3500;
GO --8
SELECT EMP_ID, EMP_NAME, HIRE_DATE
FROM EMPLOYEES
ORDER BY HIRE_DATE DESC;
GO --9
SELECT EMP_ID, EMP_NAME, JOB_NAME, SALARY
FROM EMPLOYEES
WHERE	SALARY > 1500
	AND	JOB_NAME LIKE '%MAN%';
GO --10
SELECT EMP_ID "IDPEGAWAI", EMP_NAME "NAMAPEGAWAI"
FROM EMPLOYEES
WHERE EMP_NAME LIKE '_A%';
GO --11
SELECT JOB_NAME, COUNT(JOB_NAME) "JUMLAH"
FROM EMPLOYEES
GROUP BY JOB_NAME
GO --12
SELECT (MAX(SALARY)-MIN(SALARY)) "DIFFERENCE"
FROM EMPLOYEES
GO --13
SELECT JOB_NAME, AVG(SALARY) "AVGgaji"
FROM EMPLOYEES
GROUP BY JOB_NAME
GO --14
SELECT JOB_NAME "NAMAPEKERJAAN", MANAGER_ID "IDMANAGER", SALARY "JUMLAHSALARY"
FROM EMPLOYEES
WHERE JOB_NAME LIKE '%T'
ORDER BY SALARY ASC;
GO --15
SELECT JOB_NAME "NAMAPEKERJAAN", MANAGER_ID "IDMANAGER", SUM(SALARY) "JUMLAHSALARY" 
FROM EMPLOYEES
GROUP BY JOB_NAME, MANAGER_ID
HAVING SUM(SALARY) > 1500
ORDER BY SUM(SALARY) DESC;
GO --16
SELECT EMP_ID "IDPEGAWAI", EMP_NAME "NAMAPEGAWAI", JOB_NAME "NAMAPEKERJAAN", HIRE_DATE "TANGGALPEREKRUTAN", SALARY "GAJI"
FROM EMPLOYEES
WHERE COMMISSION IS NULL;