use PresDB
go
--EXERCISE 1--
go --1
SELECT * FROM PRESIDENT
go --2
SELECT * FROM PRESIDENT
WHERE STATE_BORN IN ('MASSACHUSETTS', 'NEW YORK', 'TEXAS STATE')
go --3
SELECT * FROM PRESIDENT
WHERE DEATH_AGE IS NULL
go --4
SELECT * FROM ELECTION
WHERE ELECTION_YEAR between 1901 and 2000
	AND WINNER_LOOSER_INDIC = 'W'
ORDER BY ELECTION_YEAR ASC
go --5
SELECT * FROM STATE
WHERE YEAR_ENTERDED Between 1801 AND 1900
go --6
SELECT PRES_NAME 
FROM PRESIDENT
WHERE PRES_NAME LIKE '_E%'
go --7
SELECT * FROM PRES_MARRIAGE
WHERE NR_CHILDREN = 0
   AND PR_AGE > 40
go --8
SELECT CANDIDATE, ELECTION_YEAR 
FROM ELECTION
WHERE VOTES BETWEEN 150 AND 250
   AND WINNER_LOOSER_INDIC = 'L'
go --9
SELECT * FROM PRESIDENT
WHERE (PRES_NAME LIKE '__O%'
	and PRES_NAME LIKE 'C%') 
	or (PRES_NAME LIKE 'K%' 
	and PRES_NAME LIKE '__O%')
--ATAU--
SELECT * FROM PRESIDENT
WHERE SUBSTRING (PRES_NAME, 1, 1) IN ('C', 'K')
   AND SUBSTRING (PRES_NAME, 3, 1) = 'O'
go --10
SELECT * FROM ADMIN_PR_VP
WHERE VICE_PRES_NAME NOT LIKE '%BUSH%'
   and VICE_PRES_NAME NOT LIKE'%B%'
   and VICE_PRES_NAME NOT LIKE'%U%'
   and VICE_PRES_NAME NOT LIKE'%S%'
   and VICE_PRES_NAME NOT LIKE'%H%'
go
--EXERCISE 2--
go --1
SELECT MAX(DEATH_AGE) "MaxDeathAge" , MIN(DEATH_AGE) "MinDeathAge", AVG (DEATH_AGE) "AVGDeathAge"
FROM PRESIDENT
go --2
SELECT COUNT(STATE_BORN) "JumlahStateBorn"
FROM PRESIDENT
go --3
SELECT STATE_BORN "state_name", COUNT(STATE_BORN) "TotalPresiden"
FROM PRESIDENT
WHERE PARTY = 'Democratic'
GROUP BY STATE_BORN
HAVING COUNT(PRES_NAME) > 1
ORDER BY COUNT(PRES_NAME) DESC
go --4
SELECT PRES_NAME, COUNT(MAR_YEAR) "JumlahPernikahan", SUM(NR_CHILDREN) "JumlahAnakdariTotalPernikahan"
FROM PRES_MARRIAGE
GROUP BY PRES_NAME
HAVING SUM(NR_CHILDREN)=2
go --5
SELECT CANDIDATE, COUNT(CANDIDATE) "TotalMencalonkanPemilihanPresiden", MIN(VOTES) "MinVote", MAX (VOTES) "MaxVote"
FROM ELECTION
GROUP BY CANDIDATE
HAVING COUNT(CANDIDATE) = 2
go --6
--rumus persentase n/sum(n)*100
SELECT CANDIDATE, VOTES*100 /(SELECT SUM (VOTES) FROM ELECTION WHERE ELECTION_YEAR =1960) "MostVotesPercent"
FROM ELECTION 
WHERE ELECTION_YEAR =1960
	AND VOTES IN (SELECT MAX(VOTES) FROM ELECTION WHERE ELECTION_YEAR = 1960)
GROUP BY CANDIDATE, VOTES
go --7
SELECT PRES_NAME, COUNT (MAR_YEAR) "MARRIED"
FROM PRES_MARRIAGE
GROUP BY PRES_NAME
HAVING COUNT (MAR_YEAR) > 1
go --8
SELECT AVG (DEATH_AGE) "AVGDeathAge"
FROM PRESIDENT