CREATE TABLE STATE
(STATE_NAME		CHAR(15)	NOT NULL,
ADMIN_ENTERED	SMALLINT			,
YEAR_ENTERDED	SMALLINT			,
PRIMARY KEY (STATE_NAME));
GO
CREATE TABLE PRESIDENT
(PRES_NAME		CHAR(16)	NOT NULL,
BIRTH_YR		SMALLINT	NOT NULL,
YRS_SERV		SMALLINT	NOT NULL,
DEATH_AGE		SMALLINT			,
PARTY			CHAR(11)	NOT NULL,
STATE_BORN		CHAR(15)			,
PRIMARY KEY (PRES_NAME),
FOREIGN KEY (STATE_BORN)
	REFERENCES STATE (STATE_NAME));
GO
CREATE TABLE PRES_MARRIAGE
(PRES_NAME		CHAR(16)	NOT NULL,
SPOUSE_NAME		CHAR(16)	NOT NULL,
PR_AGE			SMALLINT			,
SP_AGE			SMALLINT			,
NR_CHILDREN		SMALLINT			,
MAR_YEAR		SMALLINT			,
PRIMARY KEY (SPOUSE_NAME, PRES_NAME),
FOREIGN KEY (PRES_NAME)
	REFERENCES PRESIDENT (PRES_NAME));
GO
CREATE TABLE PRES_HOBBY
(PRES_NAME		CHAR(16)	NOT NULL,
HOBBY			CHAR(20)	NOT NULL,
PRIMARY KEY (HOBBY, PRES_NAME),
FOREIGN KEY (PRES_NAME)
	REFERENCES PRESIDENT (PRES_NAME));
GO
CREATE TABLE ADMINISTRATION
(ADMIN_NR			SMALLINT			,
PRES_NAME			CHAR(16)	NOT NULL,
YEAR_INAUGURATED	SMALLINT	NOT NULL,
PRIMARY KEY (ADMIN_NR,PRES_NAME),
FOREIGN KEY (PRES_NAME)
	REFERENCES PRESIDENT (PRES_NAME));
GO
CREATE TABLE ADMIN_PR_VP
(ADMIN_NR		SMALLINT	NOT NULL,
PRES_NAME		CHAR(16)	NOT NULL,
VICE_PRES_NAME	CHAR(16)	NOT NULL,
PRIMARY KEY (VICE_PRES_NAME, PRES_NAME, ADMIN_NR),
FOREIGN KEY (ADMIN_NR, PRES_NAME)
	REFERENCES ADMINISTRATION (ADMIN_NR, PRES_NAME));
GO
CREATE TABLE ELECTION
(ELECTION_YEAR		SMALLINT	NOT NULL,
CANDIDATE			CHAR(16)	NOT NULL,
VOTES				SMALLINT	NOT NULL,
WINNER_LOOSER_INDIC	CHAR(1)		NOT NULL,
PRIMARY KEY (ELECTION_YEAR, CANDIDATE));
GO

